/**
 * Tailwind config (loaded from index.css via @config in v4).
 * Custom CSS color classes (e.g. bg-bg, text-text, text-muted) are not acceptable.
 * Only reusable, long-term clean code colors are allowed: slate scale, primary/danger/success
 * semantic accents, white, none. Two themes: :root (dark) and [data-theme="light"].
 * @type {import('tailwindcss').Config}
 */
module.exports = {
    darkMode: ["selector", '[data-theme="dark"]'],
    theme: {
        extend: {
            fontFamily: {
                title: ["Oswald", "sans-serif"],
            },
            backgroundImage: {
                "gradient-primary": "var(--primary-gradient)",
            },
            colors: {
                none: "transparent",
                white: "rgb(var(--color-white) / <alpha-value>)",
                primary: {
                    DEFAULT: "rgb(var(--color-primary) / <alpha-value>)",
                    10: "rgb(var(--color-primary-10) / 0.15)",
                    50: "rgb(var(--color-primary-50) / 0.9)",
                    400: "rgb(var(--color-primary-400) / <alpha-value>)",
                    500: "rgb(var(--color-primary-500) / <alpha-value>)",
                },
                danger: {
                    DEFAULT: "rgb(var(--color-danger) / <alpha-value>)",
                    10: "rgb(var(--color-danger-10) / 0.15)",
                    50: "rgb(var(--color-danger-50) / 0.4)",
                    400: "rgb(var(--color-danger-400) / <alpha-value>)",
                    500: "rgb(var(--color-danger-500) / <alpha-value>)",
                },
                success: {
                    DEFAULT: "rgb(var(--color-success) / <alpha-value>)",
                    10: "rgb(var(--color-success-10) / 0.15)",
                    50: "rgb(var(--color-success-50) / 0.4)",
                    400: "rgb(var(--color-success-400) / <alpha-value>)",
                    500: "rgb(var(--color-success-500) / <alpha-value>)",
                },
                /* Slate scale (from index.css) */
                slate: {
                    50: "rgb(var(--color-slate-50) / <alpha-value>)",
                    100: "rgb(var(--color-slate-100) / <alpha-value>)",
                    200: "rgb(var(--color-slate-200) / <alpha-value>)",
                    300: "rgb(var(--color-slate-300) / <alpha-value>)",
                    400: "rgb(var(--color-slate-400) / <alpha-value>)",
                    500: "rgb(var(--color-slate-500) / <alpha-value>)",
                    600: "rgb(var(--color-slate-600) / <alpha-value>)",
                    700: "rgb(var(--color-slate-700) / <alpha-value>)",
                    800: "rgb(var(--color-slate-800) / <alpha-value>)",
                    900: "rgb(var(--color-slate-900) / <alpha-value>)",
                    950: "rgb(var(--color-slate-950) / <alpha-value>)",
                },
            },
        },
    },
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
        "../../packages/editor/src/**/*.{js,ts,jsx,tsx}",
    ],
    safelist: [
        "opacity-60",
        "rounded-full",
        "rounded-xl",
        "rounded-2xl",
        "rounded-lg",
        "rounded-md",
        "overflow-hidden",
        "overflow-visible",
        "overflow-y-auto",
        "overflow-x-hidden",
        "p-1",
        "p-2",
        "p-3",
        "p-4",
        "p-6",
        "px-2",
        "px-3",
        "px-4",
        "px-6",
        "py-1",
        "py-2",
        "py-3",
        "py-4",
        "m-2",
        "m-4",
        "mt-1.5",
        "mt-2",
        "mb-0.5",
        "mb-1",
        "gap-1",
        "gap-2",
        "gap-3",
        "gap-4",
        "gap-6",
        "border-2",
        "border-slate-400",
        "border-slate-300",
        "border-slate-200",
        "border-slate-600",
        "border-slate-700",
        "text-xs",
        "text-sm",
        "text-base",
        "text-lg",
        "flex",
        "flex-col",
        "flex-row",
        "items-center",
        "justify-center",
        "grid",
        "w-full",
    ],
};
